import os
import re
import argparse

def squash_migrations(input_dir, output_file):
    """
    Simulated Migration Squasher. 
    In a production version, this would use a SQL parser (like pglast) 
    to track state changes. For v0.1, it provides the 'Advisor Prompt' 
    integration and a basic merger.
    """
    sql_files = sorted([f for f in os.listdir(input_dir) if f.endswith('.sql')])
    
    if not sql_files:
        print(f"No .sql files found in {input_dir}")
        return

    print(f"Found {len(sql_files)} migration files. Squashing...")
    
    with open(output_file, 'w') as outfile:
        outfile.write("-- Consolidated Schema Generated by Nexus-Squash\n")
        outfile.write("-- Part of the Sentinel Nexus Toolbox\n\n")
        
        for filename in sql_files:
            outfile.write(f"-- Source: {filename}\n")
            with open(os.path.join(input_dir, filename), 'r') as infile:
                outfile.write(infile.read())
                outfile.write("\n")

    print(f"✅ Success! Consolidated schema written to {output_file}")
    print("💡 Advisor Tip: Provide this file to Lovable/v0 to bypass migration debt.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Nexus-Squash v0.1")
    parser.add_argument("--dir", default="./migrations", help="Directory containing .sql files")
    parser.add_argument("--out", default="nexus-init.sql", help="Output filename")
    args = parser.parse_args()
    
    if not os.path.exists(args.dir):
        os.makedirs(args.dir)
        print(f"Created {args.dir} directory. Place your SQL files there and re-run.")
    else:
        squash_migrations(args.dir, args.out)
